# Generated by Django 5.2 on 2025-05-17 07:30

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=150, verbose_name='Ссылка для категории (заполняется автоматически)')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_catego_name_5111b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название товара')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Ссылка на товар (заполняется автоматически)')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание букета (не обязательно)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='стоимость')),
                ('available', models.BooleanField(default=True, verbose_name='доступно ли')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='скидка в процентах')),
                ('quantity', models.IntegerField(default=1, verbose_name='количество')),
                ('purchased', models.IntegerField(blank=True, default=0, verbose_name='количество продаж')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='main_produc_id_f4bffc_idx'), models.Index(fields=['name'], name='main_produc_name_168fc5_idx'), models.Index(fields=['-created'], name='main_produc_created_4330ad_idx')],
            },
        ),
    ]
