# Generated by Django 5.2 on 2025-09-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d', verbose_name='Фотография')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Описание изображения')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Определяет очередность фотографий', verbose_name='Порядок в галерее')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фотографии товара',
                'ordering': ['position', 'id'],
            },
        ),
    ]
