# Generated by Django 5.2 on 2025-05-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchased',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='количество'),
        ),
    ]
