# Generated by Django 5.2 on 2025-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_purchased_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/%Y/%m/%d', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'Изображение на начальной странице',
            },
        ),
    ]
