# Generated by Django 5.2 on 2025-05-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mainimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainImage',
        ),
    ]
