# Generated by Django 5.2 on 2025-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Ссылка на товар (заполняется автоматически)'),
        ),
    ]
